name: C/C++ Builds

on:
  push:
    branches:
    - 'develop'
    - 'release/*'
  pull_request:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-04-01
    steps:
      # see https://github.com/actions/checkout/issues/14
      - uses: actions/checkout@v1
      - name: disable the keychain credential helper
        run: git config --global credential.helper ""
      - name: enable the local store credential helper
        run: git config --global --add credential.helper store
      - name: add credential
        run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
      - name: tell git to use https instead of ssh whenever it encounters it
        run: 'git config --global url."https://github.com/".insteadof git@github.com:'
      - name: get submodules
        run: 'git submodule update --init --recursive'
      - uses: actions/cache@v1.1.0
        id: ccache-persistence
        with:
          path: ~/.ccache
          key: ${{ matrix.config.name }}-ccache-ccpp
          restore-keys: |
            ${{ matrix.config.name }}-ccache-ccpp
      - name: setup ccache
        run: mkdir -p ~/.ccache && echo "max_size = 300M" > ~/.ccache/ccache.conf && ccache -z && ccache -s
      - name: make
        run: make
      - name: ccache post-run
        run: ccache -s && ccache -z
