name: Linting

on:
  push:
    branches:
    - 'develop'
    - 'release/*'
  pull_request:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-clang:2021-09-08
    steps:
      # see https://github.com/actions/checkout/issues/14
      - uses: actions/checkout@v1
      - name: disable the keychain credential helper
        run: git config --global credential.helper ""
      - name: enable the local store credential helper
        run: git config --global --add credential.helper store
      - name: add credential
        run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
      - name: tell git to use https instead of ssh whenever it encounters it
        run: 'git config --global url."https://github.com/".insteadof git@github.com:'
      - name: get submodules
        run: 'git submodule update --init --recursive'
      - name: check_format
        env:
          CI: true
        run: make check_format
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: ccache cache files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{matrix.config}}-ccache-linting-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{matrix.config}}-ccache-linting-
      - name: setup ccache
        run: mkdir -p ~/.ccache && echo "max_size = 300M" > ~/.ccache/ccache.conf && ccache -z && ccache -s
      - name: clang_tidy
        env:
          CI: true
        run: make clang-tidy
      - name: ccache post-run
        run: ccache -s && ccache -z
