name: Metadata

on:
  push:
    branches:
    - 'develop'
    - 'release/*'

jobs:

  micrortps_agent:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-nuttx-focal:2021-09-08
    steps:
    - uses: actions/checkout@v1
    - name: disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: get submodules
      run: 'git submodule update --init --recursive'
    - name: microRTPS agent deploy
      run: |
        make px4_sitl_rtps
        git config --global user.name "auterion-ci"
        git config --global user.email "ci@auterion.com"
        git clone https://auterion-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Auterion/micrortps_agent.git
        cd micrortps_agent
        git fetch
        if git rev-parse --verify origin/${GITHUB_REF#refs/heads/}; then git checkout ${GITHUB_REF#refs/heads/}; else git checkout -b ${GITHUB_REF#refs/heads/}; fi
        cp -R ../build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_agent/* .
        git status
        git add src
        git commit -a -m "Update microRTPS agent source code `date`" || true
        git add idl
        git commit -a -m "Update IDL definitions `date`" || true
        git add CMakeLists.txt
        git commit -a -m "Update CMakeLists.txt `date`" || true
        git push -u origin HEAD:${GITHUB_REF#refs/heads/} || true
        cd ..
        rm -rf micrortps_agent

  system_monitord:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2021-09-08
    steps:
    - uses: actions/checkout@v1
    - name: disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: get submodules
      run: 'git submodule update --init --recursive'
    - name: system_monitord RTPS code deploy
      run: |
        sed -i -e 's/  - msg: onboard_computer_status/  - msg: onboard_computer_status\n    send: true/' msg/tools/urtps_bridge_topics.yaml
        make px4_sitl_rtps
        git config --global user.name "auterion-ci"
        git config --global user.email "ci@auterion.com"
        git clone https://auterion-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Auterion/system_monitord.git
        cd system_monitord
        git fetch
        if git rev-parse --verify origin/${GITHUB_REF#refs/heads/}; then git checkout ${GITHUB_REF#refs/heads/}; else git checkout -b ${GITHUB_REF#refs/heads/}; fi
        cp -R ../build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_agent/src/onboard_computer_status*.cpp src/rtps/
        cp -R ../build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_agent/src/onboard_computer_status*.h include/rtps/
        git status
        git add .
        git commit -a -m "Update onboard_computer_status RTPS source code `date`" || true
        git push -u origin HEAD:${GITHUB_REF#refs/heads/} || true
        cd ..
        rm -rf system_monitord

  ROS_msgs:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2021-09-08
    steps:
    - uses: actions/checkout@v1
    - name: disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Create ROS2 ws
      run: mkdir -p colcon_ws/src
    - name: PX4 ROS msgs (px4_msgs) deploy
      run: |
        mkdir -p colcon_ws/src
        git clone https://auterion-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Auterion/px4_msgs.git ${GITHUB_WORKSPACE}/colcon_ws/src/px4_msgs
        git config --global user.name "auterion-ci"
        git config --global user.email "ci@auterion.com"
        cd colcon_ws/src/px4_msgs
        git fetch
        if git rev-parse --verify origin/${GITHUB_REF#refs/heads/}; then git checkout ${GITHUB_REF#refs/heads/}; else git checkout -b ${GITHUB_REF#refs/heads/}; fi
        cd ${GITHUB_WORKSPACE}
        ROS2_WS_DIR=${GITHUB_WORKSPACE}/colcon_ws/ make update_px4_msgs
        cd colcon_ws/src/px4_msgs
        git status
        git add .
        git commit -a -m "Update message definitions `date`" || true
        git push -u origin HEAD:${GITHUB_REF#refs/heads/} || true
        cd ${GITHUB_WORKSPACE}
        rm -rf colcon_ws

  ROS2_bridge:
    needs: ROS_msgs
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2021-09-08
    steps:
    - uses: actions/checkout@v1
    - name: disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Create ROS2 ws
      run: mkdir -p colcon_ws/src
    - name: PX4 ROS2 bridge (px4_ros_com) deploy
      run: |
        mkdir -p colcon_ws/src
        git clone https://auterion-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Auterion/px4_ros_com.git ${GITHUB_WORKSPACE}/colcon_ws/src/px4_ros_com
        git config --global user.name "auterion-ci"
        git config --global user.email "ci@auterion.com"
        cd colcon_ws/src/px4_ros_com
        git fetch
        if git rev-parse --verify origin/${GITHUB_REF#refs/heads/}; then git checkout ${GITHUB_REF#refs/heads/}; else git checkout -b ${GITHUB_REF#refs/heads/}; fi
        cd ${GITHUB_WORKSPACE}
        ROS2_WS_DIR=${GITHUB_WORKSPACE}/colcon_ws/ make update_px4_ros_com
        cd colcon_ws/src/px4_ros_com
        git status
        git add .
        git commit -a -m "Update uORB RTPS code generation tools, templates and ID map `date`" || true
        git push origin HEAD:${GITHUB_REF#refs/heads/} || true
        cd ${GITHUB_WORKSPACE}
        rm -rf colcon_ws
