name: SITL Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-ros-melodic:2019-10-24
    steps:
      # see https://github.com/actions/checkout/issues/14
      - uses: actions/checkout@v1
      - name: disable the keychain credential helper
        run: git config --global credential.helper ""
      - name: enable the local store credential helper
        run: git config --global --add credential.helper store
      - name: add credential
        run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
      - name: tell git to use https instead of ssh whenever it encounters it
        run: 'git config --global url."https://github.com/".insteadof git@github.com:'
      - name: get submodules
        run: 'git submodule update --init --recursive'
      #- uses: actions/setup-python@v1
      #  with:
      #  python-version: '3.x'
      - name: build SITL
        run: make px4_sitl_default
      - name: build Gazebo
        run: make px4_sitl_default sitl_gazebo
      - name: install MAVSDK
        run: pip3 install mavsdk

      # Next step: Run the same scripts as done by Jenkins
      # https://github.com/Auterion/PX4_firmware_private/blob/develop/.ci/Jenkinsfile-SITL_tests#L144

